COUNTRIES = [
    'Nigeria', 
    'Egypt', 
    'India (Current national sample)', 
    'China', 
    'Japan', 
    'Germany', 
    'France', 
    'Spain' ,
    'United States', 
    'Canada', 
    'Brazil', 
    'Argentina', 
    'Australia', 
    'New Zealand'
]

TRAIN_COUNTRIES = [
    'Nigeria', 
    'Egypt', 
    'India (Current national sample)', 
    'Germany', 
    'United States', 
    'Canada', 
    'Argentina', 
    'Australia', 
]

EVAL_COUNTRIES = [
    'China', 
    'Japan', 
    'France', 
    'Spain' ,
    'Brazil', 
    'New Zealand'
]


ALL_COUNTRIES = [
    'Albania',
    'Andorra',
    'Angola',
    'Angola (Non-national sample)',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bangladesh',
    'Bangladesh (Non-national sample)',
    'Belarus',
    'Belgium',
    'Bolivia',
    'Bolivia (Non-national sample)',
    'Bosnia Herzegovina',
    'Brazil',
    'Brazil (Non-national sample)',
    'Britain',
    'Bulgaria',
    'Burkina Faso',
    'Canada',
    'Chile',
    'China',
    'China (Non-national sample)',
    'Colombia',
    'Colombia (Non-national sample)',
    'Croatia',
    'Cyprus',
    'Czech Rep.',
    'Czechia',
    'Denmark',
    'Ecuador',
    'Egypt',
    'Egypt (Non-national sample)',
    'El Salvador',
    'Estonia',
    'Ethiopia',
    'Ethiopia (Non-national sample)',
    'Finland',
    'France',
    'Georgia',
    'Germany',
    'Ghana',
    'Great Britain',
    'Greece',
    'Guatemala',
    'Guatemala (Non-national sample)',
    'Honduras',
    'Honduras (Non-national sample)',
    'Hong Kong SAR',
    'Hungary',
    'Iceland',
    'India (Current national sample)',
    'India (Non-national sample)',
    'India (Old national sample)',
    'Indonesia',
    'Indonesia (Non-national sample)',
    'Iran',
    'Iraq',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Ivory Coast (Non-national sample)',
    'Japan',
    'Jordan',
    'Jordan (Non-national sample)',
    'Kazakhstan',
    'Kenya',
    'Kuwait',
    'Kyrgyzstan',
    'Latvia',
    'Lebanon',
    'Libya',
    'Lithuania',
    'Macau SAR',
    'Malaysia',
    'Maldives',
    'Mali',
    'Mali (Non-national sample)',
    'Mexico',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Morocco (Non-national sample)',
    'Myanmar',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Nigeria',
    'Nigeria (Non-national sample)',
    'North Macedonia',
    'Northern Ireland',
    'Norway',
    'Pakistan',
    'Pakistan (Non-national sample)',
    'Palest. ter.',
    'Peru',
    'Philippines',
    'Philippines (Non-national sample)',
    'Poland',
    'Poland (Non-national sample)',
    'Portugal',
    'Puerto Rico',
    'Romania',
    'Russia',
    'Russia (Non-national sample)',
    'S. Africa',
    'S. Africa (Non-national sample)',
    'S. Korea',
    'Senegal',
    'Senegal (Non-national sample)',
    'Serbia',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'South Korea',
    'Spain',
    'Sweden',
    'Switzerland',
    'Taiwan',
    'Taiwan ROC',
    'Tajikistan',
    'Tanzania',
    'Tanzania (Non-national sample)',
    'Thailand',
    'Tunisia',
    'Turkey',
    'Uganda',
    'Ukraine',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Venezuela',
    'Venezuela (Non-national sample)',
    'Vietnam',
    'Vietnam (Non-national sample)',
    'Zimbabwe'
]